By accessing or using LavaLinx and by signing up as a User of LavaLinx you agree to adhere to and be bound by the terms and conditions in this Agreement. Please read this Agreement carefully before accessing or using LavaLinx.  If you can not accept this Agreement, you may not access or use LavaLinx.
In this Agreement, LavaLinx, the LavaLinx Service, all services related to it, including all text, images, photographs, user interface, "look and feel," data and other content (including the selection, coordination and arrangement of such content) are referred to as the "Web Site" or "Service." Any User determined by LavaLinx to have violated the terms and conditions of this agreement is subject to immediate termination of services.

LavaLinx reserves the right to change the Terms and Conditions of the Agreement and such modifications shall be effective immediately. Users should visit this page periodically to review the Terms and Conditions because they legally determine the conditions under which they are allowed to use the Service.  A User’s continued access of the Web Site or Service shall be deemed acceptance of the modified agreement.
 
1. Services Generally.
(a) Description. The Service is an online offering where individuals or entities (collectively, "Users") can manage and exchange links with other web site owners inside or outside the LavaLinx network.
(b) License. Users must be paid subscribers to access the LavaLinx internal trading network. Users may add up to 4 web sites to their account. LavaLinx retains the right to review and decline sign ups or applications for service for websites that display or publish content related to illegal activities, gambling, pornography, hate or racism. LavaLinx retains the right to deny service to sites that publish turnkey content, spam sites, trap sites, lead generating sites, credit repair sites, and any other site that LavaLinx deems to have no content of value. Under this license, Users cannot sell, assign, or transfer rights of links acquired or used in the LavaLinx system.
(c) Payment. Users must pay for the Service via credit card or other payment method authorized at the time of registration.  If Users pay by credit card, they will be required to provide a valid credit card number and billing address when registering. The payment policies for Users may change at any time. Services are paid for in advance and accounts in default in excess of 30 days will be suspended. 
(d) Pricing. Pricing is subject to change upon 30 days notice from LavaLinx. Such notice may be provided at any time by posting the changes to the LavaLinx.com website (www.LavaLinx.com) or the Service itself.
(e) Refunds. LavaLinx has the right to cancel orders and may provide refunds at its sole discretion. LavaLinx retains the right to modify or change this policy at any time without notice. 
(f) Cancellations. Users may cancel subscription services at any time by contacting the company directly via the Contact Us page, accessed through the Web Site. LavaLinx reserves the right to delete accounts after one year of account inactivity. It is the User’s responsibility to download, copy, or export data relating to their account. No additional data backup methods are available. 
2. Eligibility and Use.
(a) Eligibility. To register as a User, you must be at least 18 years of age, accept the Agreement, and complete the registration procedure. By registering, Users represent and warrant that (1) they meet these eligibility requirements, (2) the information they include as part of the registration process is complete and accurate, and (3) if they are registering on behalf of an entity, that they are authorized to bind that entity to this Agreement. LavaLinx is not required to accept a Users registration.
(b) Permitted Uses. Users may access and use the Service only according to this Agreement and any posted policies and procedures that appear on the Web Site. Any use of the Web Site is at a Users own risk and responsibility. Users may display the Web Site on an internet access device and not print pages from the Web Site. Printing lists of partners or link traders inside the LavaLinx system is strictly prohibited. Providing copies of, selling or reselling link trading partner lists generated from the LavaLinx system is strictly prohibited. Users agree not to modify the Web Site, or any portion of it, except by the express written consent of LavaLinx. Users may not frame, or use any framing techniques to enclose any portion of the Web Site without the written consent of LavaLinx. Users may not use meta tags or any other "hidden text" that utilize the LavaLinx trademark or company name without the written consent of LavaLinx.
(c) Prohibited Uses. Users may not broadcast, circulate, distribute, download, perform, publish, rent, reproduce, sell, store, transmit or create lists, content or works from the Web Site. Users must comply with all applicable laws (including any applicable export control laws) in connection with using the Service.  Further limitations may be set forth in any written or on-screen notice from LavaLinx.
(d) Deliberate Link Cheating. Users must reciprocate to partner websites in a way agreeable to both parties involved in the link exchange. “Link Cheating”, the act of not reciprocating agreed to value for a link, is strictly prohibited. Link Cheaters are to be reported to LavaLinx and will be provided a warning. If within 30 days the User does not correct the violation, the User’s account will be suspended.
(e) Users agree not to transmit, distribute, post, communicate or store information on, to, or through the Web Site that:
            (i) is copyrighted, unless Users are the copyright owner;
            (ii) reveals trade secrets, unless Users own them;
            (iii) infringes on any intellectual property, privacy, or publicity rights of others;
            (iv) is obscene, defamatory, threatening, harassing, abusive, hateful, or embarrassing to others;
            (v) is sexually-explicit;
            (vi) constitutes advertisements or solicitations of business, chain letters, or pyramid schemes; or
            (vii) contains viruses, Trojan horses, worms, time bombs, or other electronic data that are intended to damage, interfere with, surreptitiously intercept, or expropriate any LavaLinx system, data, or information.
(f) Users further agree not to:
            (i) use any incomplete, false, or inaccurate information for purposes of registering as a User;
            (ii) delete or revise any information of another User or of LavaLinx;
            (iii) take any action that imposes an unreasonably large load on the Web Site's infrastructure;
            (iv) attempt to interfere with the proper working of this Service;
            (v) attempt to use any software, tool, or other device (including browsers, spiders, robots, avatars, agents, or the like) to navigate or search this Web Site other than with the search engines available from LavaLinx and other commercially available third party web browsers (e.g., Firefox and Microsoft Internet Explorer); or
            (vi) attempt to decipher, decompile, disassemble, or reverse engineer any of the software underlying the Web Site.
 (g) Users are prohibited from attempting to violate the security of the Web Site, including:
            (i) accessing data not intended for Users or logging into a server or account that Users are not authorized to access;
            (ii) attempting to probe, scan, or test the vulnerability of the Web Site or to breach security or authentication measures;
            (iii) attempting to interfere with the service of any user, host or network, including submitting a virus to, overloading, "flooding", "spamming", "mailbombing," or "crashing" the Web Site;
            (iv) sending unsolicited e-mail, including promotions and/or advertising of products or services; or
            (v) forging any TCP/IP packet header or any part of the header information in any e-mail or posting.
(4) Violations of security of the Web Site may result in civil or criminal liability. LavaLinx will investigate any violation and may cooperate with law enforcement authorities in prosecuting Users involved in such violations.
(a) Operation of Web Site. LavaLinx reserves the right to terminate Users ability to communicate with, or post to, the Web Site at any time. LavaLinx will take reasonable efforts not to disclose any information Users send to the Web Site.  LavaLinx may disclose any information to the extent necessary to satisfy any applicable law, regulation, legal process or governmental request.  LavaLinx may edit, refuse to post, or to remove any information or materials from the Web Site.
(b) Accessibility. LavaLinx shall not be responsible for any delays or interruptions of, errors, or omissions contained in the Web Site. Although LavaLinx will use reasonable efforts to make the Web Site and Service accessible, LavaLinx makes no representation, warranty or covenant that the Web Site will be available at any specific time since various circumstances may prevent or delay availability. LavaLinx may discontinue or modify the Web Site, may change or eliminate any transmission method, and may change transmission speeds or other signal characteristics. LavaLinx shall not be responsible for any loss, cost, damage or liability that may result in such events.
(c) Termination of Access. LavaLinx reserves the right to reject, cancel, or terminate Users access to the LavaLinx at any time without notice. Users agree that LavaLinx shall not be liable to Users or any third party for any rejection, cancellation, or termination of such access.

3. Responsibility for Content
(a) Web Site.  LavaLinx shall not be responsible for any use that is or is not made of the Web Site. LavaLinx makes no representations, warranties or guarantees regarding the truthfulness, accuracy, or reliability of any information that is communicated to and from the Web Site.  LavaLinx does not endorse any opinions expressed by any User. Each User agrees and acknowledges that he engages in link trading at his own risk and that he is responsible for taking any actions necessary to determine whether its use will infringe any third party intellectual property, privacy, or publicity right. LavaLinx shall not be held responsible for any negative actions by Search Engines resulting in a banned site, reduced or eliminated Page Rank, or a drop in search result rankings.
(b) Downloads. LavaLinx does not guarantee that data made available on the Web Site will be free of infection or viruses, worms, Trojan horses, or other code that manifests contaminating or destructive properties. It is Users responsibility for implementing sufficient safeguards and procedures to ensure that any such data is free from such problems.

4. Rights to Use.
(a) User Information. For any information or media provided by User in connection with use of the Service (collectively, the "User Information"), LavaLinx has all rights necessary to use the User Information to provide the Service.
(b) License. Upon submission of User Information to the Service, User grants LavaLinx a royalty-free, perpetual, irrevocable, sublicenseable, exclusive, worldwide license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, communicate to the public, moral right, perform, display, and/or incorporate in other works, in any form, media, or technology now known or later developed for the full term of any intellectual property rights that may exist in such User Information to the extent necessary to provide the Service.
(c) LavaLinx Ownership. The contents of this Web Site, including the user interface, text, link trading partners and lists, graphics, logos, icons, movies, images, audio files, data compilations, the selection and format thereof, as well as the underlying software and databases are the property of LavaLinx and are protected by U.S. and international copyright and trademark laws.
(d) Intellectual Property.  LavaLinx owns all right, title and interest in and to all copyright, trademarks, programming code, service mark, patent, trade secret or other intellectual property and proprietary rights in and to the Web Site to the fullest extent provided under U.S. and international law. Users shall not remove, conceal or alter any copyright notice, byline information, disclaimer, restriction, or other notice on the Web Site. Users shall not use or permit any third party to use the name, trademarks, trade names, or trade dress of LavaLinx without the written consent of LavaLinx.
(e) Third Party Rights. If Users believe any content appearing on the Web Site infringes another party’s rights, please to notify us of this infringement.

5. Registration, Password, User Identity.
(a) User Identity. When registering, Users will create an identity ("User Identity"). The User Identity will include certain Web Site information, including the industry in which the Web Site operates. The information provided may not be treated as confidential.
(b) Passwords and Access. Users shall keep confidential the User Identity, registration identification, and password(s). Users shall immediately notify LavaLinx if Users learn of or suspect: (i) any loss or theft of a User Identity, registration identification or password, or (ii) any unauthorized use of Users registration identification or password or of the Web Site. In such an event, LavaLinx may impose additional security obligations on Users.
(c) Security Breaches. If any unauthorized person obtains access to the Web Site as a result of any act or omission by a User, that User shall use his best efforts to ascertain the source and manner of acquisition and shall promptly notify LavaLinx. Users shall cooperate and assist in any investigation relating to any such unauthorized access.
(d) Inactivity. LavaLinx will maintain and grant Users access to accounts until one year after the the date of the last activity on the account. If Users have not accessed the Web Site after that time, LavaLinx may delete that information. Paid user accounts will not be deemed as inactive so long as the user keeps their payment current. 
6. Privacy. LavaLinx will use reasonable efforts to follow its privacy policy.  Such privacy policy may be changed from time to time at LavaLinx's sole discretion.  LavaLinx does not assume any responsibility or liability for any information submitted to the Web Site or for the misuse of any User Information submitted by Users or any other person, including any information accessed by a hacker or by any other malicious act.

7. Disclaimers; Limitations of Liability.
(a) Release from Claims. The Service serves as a venue for the exchange of web site links. LavaLinx does not screen or censor any information or material posted to the Web Site. Although LavaLinx makes reasonable efforts to determine the identity of Users, LavaLinx does not confirm the specific identity of any User. Accordingly, if a User has a dispute with another User, Users release LavaLinx from claims, demands, and damages of every kind and nature arising out of or in any way connected with such disputes.
(b) Disclaimer of Warranties. THE SERVICE IS PROVIDED "AS IS." LAVALINX MAKES NO REPRESENTATION OR WARRANTY OF ANY KIND RELATING IN ANY WAY TO THE WEB SITE, INCLUDING ANY USER IDENTITY OR LINKED CONTENT.  LAVALINX DISCLAIMS TO THE MAXIMUM EXTENT PERMITTED BY LAW, ANY AND ALL SUCH REPRESENTATIONS AND WARRANTIES. LAVALINX SPECIFICALLY DISCLAIMS TO THE MAXIMUM EXTENT PERMITTED BY LAW ANY AND ALL (i) WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, (ii) WARRANTIES AGAINST INFRINGEMENT OF ANY THIRD PARTY INTELLECTUAL PROPERTY OR PROPRIETARY RIGHTS, (iii) WARRANTIES RELATING TO DELAYS, INTERRUPTIONS, ERRORS, OR OMISSIONS IN THE WEB SITE, OR ANY PART THEREOF, (iv) WARRANTIES RELATING TO THE TRANSMISSION OR DELIVERY OF THE WEB SITE, AND (v) WARRANTIES OTHERWISE RELATING TO PERFORMANCE, NONPERFORMANCE, OR OTHER ACTS OR OMISSIONS BY LAVALINX OR ANY THIRD PARTY. FURTHER, LAVALINX DOES NOT WARRANT THAT THE WEBSITE WILL MEET USERS NEEDS OR REQUIREMENTS OR THE NEEDS OR REQUIREMENTS OF ANY OTHER PERSON.
(c) Limitation of Remedy. NEITHER LAVALINX NOR ANY THIRD PARTY SHALL BE LIABLE TO USERS OR ANY OTHER PERSON FORANY REMEDY, LIABILITY, DAMAGES, COSTS, OR LOSSES RELATING TO THE WEB SITE OR ANY OTHER CONTENT, WHETHER ARISING UNDER THESE TERMS OR ANY APPLICABLE LAW.
(d) Exclusion of Consequential Damages. IN NO EVENT SHALL LAVALINX OR ANY THIRD PARTY BE LIABLE TO USERS OR ANY OTHER PERSON FOR CONSEQUENTIAL, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR INDIRECT DAMAGES (INCLUDING LOST PROFITS, LOSS OF BUSINESS OR DATA, BUSINESS INTERRUPTION, TRADING LOSSES, AND DAMAGES THAT RESULT FROM INACCURACY OF THE INFORMATION OR INCONVENIENCE, DELAY, OR LOSS OF THE USE OF THE SERVICE) ARISING UNDER OR IN ANY WAY RELATED TO THE WEB SITE OR ANY OTHER CONTENT, EVEN IF LAVALINX OR ANY THIRD PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES.
(e) No Guarantee. LAVALINX DOES NOT WARRANT OR GUARANTEE ANY IMPROVEMENT IN ORGANIC SEARCH ENGINE RANKINGS AS A RESULT OF USING THIS SERVICE. Each User agrees and acknowledges that he engages in link trading at his own risk and that he is responsible for taking any actions necessary to determine whether its use will infringe any third party intellectual property, privacy, or publicity right. LavaLinx shall not be held responsible for any negative actions by Search Engines resulting in a banned site, reduced or eliminated Page Rank, or a drop in search result rankings.

8. Indemnification. Users agree to defend, indemnify and hold harmless LavaLinx and its subsidiaries, affiliates, officers, agents, partners and employees from all liabilities or claims of any third party arising out of Users violation of this Agreement.
 
9. Linked Content. The Web Site may contain links to third party web sites or other services (the "Linked Content"). The Linked Content is not under the control of LavaLinx and LavaLinx therefore is not responsible for the Linked Content. LavaLinx provides Linked Content to Users only as a convenience and the inclusion of such Linked Content is not an endorsement by LavaLinx. If Users decide to access any Linked Content, Users do so at their own risk.

10. Termination. LavaLinx reserves the right to terminate Users access to all or a portion of the Service without notice. In the event of such termination, LavaLinx will determine the amount of any refund (if any) to be paid to User as a result of such termination.  Should Users use of the Service result from a material breach of this Agreement, or any other agreement between LavaLinx and User, User shall not be entitled to any refund. Termination of the Service will result in the deactivation or deletion of the Account or access to the Account, and immediate deletion of all data in the Account. LavaLinx reserves the right to refuse service to anyone for any reason at any time.
11. Email communications. LavaLinx will generally use email to communicate with User. By using the Service, Users agree to receive status notifications, a monthly newsletter, and carefully selected special offers and promotions, and third-party services LavaLinx believes could be of value to User.  Users are free to unsubscribe from such communications at anytime. Users personal identifying information will never be disclosed or shared with another party without Users explicit permission.

12. General. This Agreement sets forth the entire agreement and understanding of the parties with respect to the subject matter and supersedes any and all prior oral or written agreements and understandings, including any and all contemporaneous oral agreements and understandings (excluding any associated agreements required by LavaLinx [e.g., privacy policy] as a condition precedent to Users use of the Service), between Users and LavaLinx regarding this Agreement. No modification, amendment, or waiver of this Agreement shall be binding unless evidenced in writing and signed by LavaLinx. If any provision of this Agreement is held by a court of competent jurisdiction to be invalid, void, or unenforceable, then such provision shall be deemed null and void, but the remaining provisions shall continue in full force without being impaired or invalidated in any way. The language of this Agreement shall be deemed to be the language mutually chosen by the parties and no rule of strict construction shall be applied against or in favor of either party hereto. The section headings and other headings contained in this Agreement were selected for convenience and shall not affect the meaning or interpretation of this Agreement. This Agreement shall be governed by the substantive law of the State of Utah, without reference to any choice of law rules that would result in the application of the substantive law of any other jurisdiction. The parties agree that any disputes arising out of or relating to this Agreement shall be submitted to arbitration and then to the federal courts having jurisdiction in Salt Lake City, Utah, or state courts having jurisdiction in the area in which such federal courts have jurisdiction, and the parties consent to the personal jurisdiction of such courts in respect of such disputes. Users may not assign or otherwise transfer (by operation of law or otherwise) any of Users rights or duties hereunder unless LavaLinx agrees in writing after receiving prior written notice. Any attempted assignment or other transfer without the requisite consent shall be null and void ab initio. LavaLinx may assign or otherwise transfer any of its rights or the performance of any of its duties. The waiver by LavaLinx of a breach or a violation of any provision of this Agreement shall not operate as or be construed to be a waiver of any subsequent breach or violation of any provision of this Agreement.

Any rights not expressly granted herein are reserved by LavaLinx.
LavaLinx is owned and operated by LAVABALL INC., a Utah corporation.
Copyright 2011 Lavaball, Inc.